// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingBook.Infrastructure.Persistence;

#nullable disable

namespace TradingBook.Infrastructure.Migrations
{
    [DbContext(typeof(TradingBookDbContext))]
    partial class TradingBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("TradingBook.Infrastructure.Persistence.Entities.AppInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppInfo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusText = "Application started."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
